"""allow guest users in assistant training logs

Revision ID: 13518dd95fc3
Revises: 4246655a1fae
Create Date: 2026-03-13 15:55:44.273566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13518dd95fc3'
down_revision = '4246655a1fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_training_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_training_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
